name: Build and Push to Dockerhub test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: Download EarnApp installer
        run: wget -qO- https://brightdata.com/static/earnapp/install.sh > ./earnapp.sh

      - name: Get version
        run: grep VERSION= ./earnapp.sh | cut -d'"' -f2 > ./version

      # Build the Docker image first
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: madereddy/earnapp:{{ GITHUB_RUN_NUMBER }}
      
      # Slim the Image
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: madereddy/earnapp:{{ GITHUB_RUN_NUMBER }}
          tag: "slim-{{github.run_number}}"
        
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
           
      # Push to the registry
      - run: | 
         docker tag madereddy/earnapp:slim-{{ GITHUB_RUN_NUMBER }} ${{ secrets.DOCKERHUB_USERNAME }}/madereddy/earnapp:slim-{{ GITHUB_RUN_NUMBER }}
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/madereddy/earnapp:slim-{{ GITHUB_RUN_NUMBER }}
