name: Build and Push to Dockerhub test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Download EarnApp installer
        run: wget -qO- https://brightdata.com/static/earnapp/install.sh > ./earnapp.sh

      - name: Get version
        run: grep VERSION= ./earnapp.sh | cut -d'"' -f2 > ./version

      # Build the Docker image first
      - uses: docker/build-push-action@v4
        with:
          push: false
          tags: madereddy/earnapp:{{ GITHUB_RUN_NUMBER }}
      
      # Slim the Image
      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: madereddy/earnapp:{{ GITHUB_RUN_NUMBER }}
          tag: "slim-{{github.run_number}}"
           
      # Push to the registry
      - run: | 
         docker tag madereddy/earnapp:slim-{{ GITHUB_RUN_NUMBER }} ${{ secrets.DOCKERHUB_USERNAME }}/madereddy/earnapp:slim-{{ GITHUB_RUN_NUMBER }}
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/madereddy/earnapp:slim-{{ GITHUB_RUN_NUMBER }}
