name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu:20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version tag from EarnApp installer
        run: VERSION=$(wget -qO- https://brightdata.com/static/earnapp/install.sh | grep VERSION= | cut -d '"' -f 2)

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ madereddy/earnapp:$(VERSION) }}
            # cwlu2001/earnapp:latest
